[project]
name = "stratego"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = [
  "textarena",
  "langchain-ollama",
  "langchain-core",
  "pydantic>=2",
]

[project.scripts]
stratego = "stratego.main:cli"
